# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_COMPANY_NAME
ARG NEXT_PUBLIC_HEADER_LOGIN_URL
ARG NEXT_PUBLIC_DOCS_URL
ARG NEXT_PUBLIC_CLIENTS_COUNT
ARG NEXT_PUBLIC_NETWORK_SPEED
ARG NEXT_PUBLIC_CONSULTATION_EMAILS
ARG NEXT_PUBLIC_CONSULTATION_PHONES
ARG NEXT_PUBLIC_SUPPORT_EMAILS
ARG NEXT_PUBLIC_SUPPORT_PHONES
ARG NEXT_PUBLIC_SOCIAL_LINKS

ENV NEXT_PUBLIC_COMPANY_NAME=$NEXT_PUBLIC_COMPANY_NAME
ENV NEXT_PUBLIC_HEADER_LOGIN_URL=$NEXT_PUBLIC_HEADER_LOGIN_URL
ENV NEXT_PUBLIC_DOCS_URL=$NEXT_PUBLIC_DOCS_URL
ENV NEXT_PUBLIC_CLIENTS_COUNT=$NEXT_PUBLIC_CLIENTS_COUNT
ENV NEXT_PUBLIC_NETWORK_SPEED=$NEXT_PUBLIC_NETWORK_SPEED
ENV NEXT_PUBLIC_CONSULTATION_EMAILS=$NEXT_PUBLIC_CONSULTATION_EMAILS
ENV NEXT_PUBLIC_CONSULTATION_PHONES=$NEXT_PUBLIC_CONSULTATION_PHONES
ENV NEXT_PUBLIC_SUPPORT_EMAILS=$NEXT_PUBLIC_SUPPORT_EMAILS
ENV NEXT_PUBLIC_SUPPORT_PHONES=$NEXT_PUBLIC_SUPPORT_PHONES
ENV NEXT_PUBLIC_SOCIAL_LINKS=$NEXT_PUBLIC_SOCIAL_LINKS

RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
